# Generated by Django 4.2.5 on 2023-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=25)),
                ('phno', models.IntegerField(max_length=10)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
