# Generated by Django 4.2.5 on 2023-09-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_person_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phno',
            field=models.IntegerField(max_length=12),
        ),
    ]
